### ISSUE TITLE
main does not compile: table_catalog calls new_ns_lock removed from StorageAPI

### ISSUE THREAD

**Issue by simon-escapecode** [rustfs/rustfs#3373]
Commit a85cc035 (#3365) removed the namespace lock from the StorageAPI surface, but rustfs/src/table_catalog.rs line 1548 (added in #3342) still calls new_ns_lock on a generic storage handle, so cargo cannot compile the rustfs lib:

    error[E0599]: no method named new_ns_lock found for struct Arc<S> in the current scope
        --> rustfs/src/table_catalog.rs:1548:14
        = note: the following trait defines an item new_ns_lock, perhaps you need to implement it:
                candidate #1: NamespaceLocking

Test and Lint is failing on main's own CI for a85cc035. The two changes appear to have merged green individually but conflict semantically.

NamespaceLocking is implemented for the concrete ecstore types (SetDisks, Sets, LockingConfigStorage), so the fix is likely either implementing it for the generic handle used by table_catalog or routing that call through the concrete type.

**Comment by loverustfs** [comment]
Fixed, thx.
